version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./sessions:/var/www/html/sessions
    environment:
      DB_HOST: db
      DB_DATABASE: pinto
      DB_USERNAME: postgres
      DB_PASSWORD: pinto1305
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pinto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pinto1305
    ports:
      - "5433:5432"

volumes:
  db_data: